### ISSUE TITLE
Nitrogen restore doesn't work on i3 startup on Arch Linux

### ISSUE THREAD

**Issue by emanuelserpa** [l3ib/nitrogen#111]
I spent some hours but now I give up, nitrogen seems that doesn't work at all trying to restore the wallpaper on i3, only works when I'm already logged and write "nitrogen --restore" in the terminal.

Now I'm putting the output from the terminal below
 
 % nitrogen --restore
/home/evasb/.gtkrc-2.0:1: error: invalid keyword 'font_name', expected valid keyword - e.g. `style'
UNKNOWN ROOT WINDOW TYPE DETECTED (Tilda), please file a bug
/home/evasb/.gtkrc-2.0:1: error: invalid keyword 'font_name', expected valid keyword - e.g. `style'

Thanks for your attention.

**Comment by daf** [comment]
Ah, this is because it's finding Tilda and I haven't added an exception for that to ignore like conky.  I'll add one.  In the mean time, you can use `--force-setter=xwindows` in your restore line.

**Comment by RFGMM** [comment]
I got a solution:

install feh and instead of nitrogen --restore put this on autostart

in case of using

[:0.0]

feh --bg-fill $(head -n 7 .config/nitrogen/bg-saved.cfg | tail -n 1 | cut -c 6-) &
or
in case of using

[xin_-1]

feh --bg-fill $(head -n 2 .config/nitrogen/bg-saved.cfg | tail -n 1 | cut -c 6-) &

**Comment by emanuelserpa** [comment]
What @daf suggested worked. Thanks!
