### ISSUE TITLE
Nitrogen não reconhece o arquivo .avif

### ISSUE THREAD

**Issue by MatanzaBR** [l3ib/nitrogen#165]
**Nitrogen does not recognize the .avif file**

**Nitrogen não reconhece o arquivo .avif**

$ file cat\ astronaut.avif 
cat astronaut.avif: ISO Media, AVIF Image

![Captura de tela_2024-02-25_01-17-16](https://github.com/l3ib/nitrogen/assets/33039864/6b9b15a5-b666-4171-89e4-da9c964b9f89)

![Captura de tela_2024-02-25_01-14-01](https://github.com/l3ib/nitrogen/assets/33039864/2e0d3324-9185-4a8a-b07b-3deb7f7b0228)

**Comment by 0xhenrique** [comment]
It's been quite some years since last update from Nitrogen dev, I could patch this but I don't think he would merge it. Anyway, I managed to make nitrogen work with ``avif`` files.
First of all clone this repo, preferably uninstall your current nitrogen.
After cloning the repo, go to the folder and search for the file `src/Util.cc`, search for the function `is_image(std::string file)` and change the body of the function for this:
```
bool is_image(std::string file) {
	if (file.find(".png")  != std::string::npos ||
		file.find(".PNG")  != std::string::npos ||
		file.find(".jpg")  != std::string::npos ||
		file.find(".JPG")  != std::string::npos ||
		file.find(".jpeg") != std::string::npos ||
		file.find(".JPEG") != std::string::npos ||
		file.find(".gif")  != std::string::npos ||
		file.find(".GIF")  != std::string::npos ||
		file.find(".svg")  != std::string::npos ||
                file.find(".SVG")  != std::string::npos ||
                file.find(".avif")  != std::string::npos ||
        	file.find(".AVIF")  != std::string::npos)
		return true;

	return false;
}
```

After doing this you will need to compile everything (make sure you don't have nitrogen installed at this point).
`$ make`
`$ sudo make install`

Hope it helps you.

![image](https://github.com/l3ib/nitrogen/assets/23097578/08e34b6b-451b-4c61-8a2d-04e72a7dd2c0)

**Comment by MatanzaBR** [comment]
**Viewing .avif file using Nitrogen**

**Visualizando arquivo  .avif no Nitrogen**

![Visualizando arquivo  avif no Nitrogen](https://github.com/l3ib/nitrogen/assets/33039864/4ea1b9e4-6fd3-4f90-9fd1-8e0963fd2d9b)
