### ISSUE TITLE
Feauture Request: Execute script on wallpaper changed

### ISSUE THREAD

**Issue by Goodmind** [l3ib/nitrogen#57]
Hello,

I think it would be nice to be able execute some script when wallpaper changed

**Comment by JamesWrigley** [comment]
I think this is somewhat outside of nitrogen's scope? If you want it to be run on startup/login, then there should be other ways to do it (i.e. autostart.sh in openbox).

**Comment by Goodmind** [comment]
I want to set lightdm wallpaper when nitrogen wallpaper is changed

**Comment by bbenne10** [comment]
you could also just write a wrapper script (called `nitrogen`, if you have muscle memory) and place it before nitrogen's install path in `$PATH`. Something like: 

```
user_path=`dbus-send --print-reply=literal --system --dest=org.freedesktop.Accounts /org/freedesktop/Accounts org.freedesktop.Accounts.FindUserByName string:$USER`
nitrogen
img_path=`cat $NITROGEN_HOME/* | grep "file" | cut -d "=" -f2 | head -n 1`
dbus-send --print-reply --system --dest=org.freedesktop.Accounts $user_path org.freedesktop.Accounts.User.SetBackgroundFile string:$img_path
```

Would this work? Or am I missing something?

**Comment by Goodmind** [comment]
But if it triggered when I changed wallpaper from gui?

**Comment by bbenne10** [comment]
No - it won't write any intermediate wallpapers to lightdm, but it will write the wallpaper out to the lightdm configuration whenever you close nitrogen. This should FUNCTIONALLY be the same (and might be better, since you're not writing all those intermediate changes out to the lightdm config - though you will write the wallpaper every time you open nitrogen, whether or not you change the wallpaper). 

Currently, Nitrogen doesn't do anything but write to it's output file when you save a wallpaper. The developer has said that what you're asking is out of scope (and I tend to agree). There're two possible solutions here: Either you follow the file with something like [fsniper](https://github.com/l3ib/fsniper) (which is the solution you've already got), or you wrap nitrogen like I've said above. 

Waiting for changes to the file seems superfluous to me (unless you're already using fsniper or similar), so I think the best solution is to write the file after nitrogen closes (and the user has presumably changed their wallpaper)

An update to the above that doesn't change the lightdm config if the user is just doing `nitrogen --resore`:

```
user_path=`dbus-send --print-reply=literal --system --dest=org.freedesktop.Accounts /org/freedesktop/Accounts org.freedesktop.Accounts.FindUserByName string:$USER`
nitrogen $@
if [ "$1" != "--restore" ]; then 
    img_path=`cat $NITROGEN_HOME/* | grep "file" | cut -d "=" -f2 | head -n 1`
    dbus-send --print-reply --system --dest=org.freedesktop.Accounts $user_path  org.freedesktop.Accounts.User.SetBackgroundFile string:$img_path
fi
```

**Comment by Goodmind** [comment]
Thanks for your solution! It works!

```/usr/local/bin/nitrogen```:
```
config_path="${XDG_CONFIG_HOME:-$HOME/.config}/nitrogen"
user_path=`dbus-send --print-reply=literal --system --dest=org.freedesktop.Accounts /org/freedesktop/Accounts org.freedesktop.Accounts.FindUserByName string:$USER`
/usr/bin/nitrogen $@
if [ "$1" != "--restore" ]; then 
    img_path=`cat $config_path/* | grep "file" | cut -d "=" -f2 | head -n 1`
    dbus-send --print-reply --system --dest=org.freedesktop.Accounts $user_path  org.freedesktop.Accounts.User.SetBackgroundFile string:$img_path
fi
```

**Comment by bbenne10** [comment]
I'm glad this works for you. Since this is solved, I'm sure the owners of the repo would appreciate you closing the issue :)
