### ISSUE TITLE
Translations installed but not used

### ISSUE THREAD

**Issue by napcok** [l3ib/nitrogen#95]
Hello,
I just installed nitrogen 1.6.1, translation files present in filesystem but not loaded.

**Comment by Vladimir-csp** [comment]
confirming this.

**Comment by dglava** [comment]
Potentially relevant output of strace:
```
open("/usr//locale/en_US.UTF-8/LC_MESSAGES/nitrogen.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr//locale/en_US.utf8/LC_MESSAGES/nitrogen.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr//locale/en_US/LC_MESSAGES/nitrogen.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr//locale/en.UTF-8/LC_MESSAGES/nitrogen.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr//locale/en.utf8/LC_MESSAGES/nitrogen.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr//locale/en/LC_MESSAGES/nitrogen.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
```

I think the problem is the double slash in the path. It looks under `/usr//locale/...` instead of `/usr/locale/...`. Perhaps there's an unnecessary slash somewhere in the source or make files?

**Comment by daf** [comment]
Thanks for investigating, @dglava - you're really onto something here.  It looks like I pulled that line containing `${DATADIRNAME}` from http://inti.sourceforge.net/tutorial/libinti/internationalization.html#IAL03 .  I'm trying to track down what's a more modern/appropriate integration with configure.ac.

Things like Preferences/Apply all come from [GTK Stock Icons](https://developer.gnome.org/gtkmm/stable/namespaceGtk_1_1Stock.html#a4cbfe0fbbd18329f560bb225081743c9), which also appear to be deprecated, which may explain why their translations appear missing.  That'll have to be an additional fix.

**Comment by daf** [comment]
Also in my local build, I'm seeing that directory defined:

```
m4/gettext.m4
329:    DATADIRNAME=share
330:    AC_SUBST(DATADIRNAME)
```

and translations for nitrogen are installing into the proper place, but I can't ever figure out how to get them to display for me.

**Comment by daf** [comment]
Wait, this seems to be working for me?!?

![image](https://user-images.githubusercontent.com/228715/37528791-e50e1f4c-290b-11e8-8275-e1f38fceff04.png)

**Comment by daf** [comment]
I guess this means the stock icons are translating, but nitrogen's custom messages are not - otherwise we'd see "Zoomed Fill" "Full Screen" etc translated.  Back to the drawing board...

**Comment by dglava** [comment]
Regarding the missing translations for certain strings: it's because they're not defined in the po/pot file. For example none of the strings from the "Preferences" window, like "View Options" or "Icon with Captions",  are in there.

It seems that not all source files are mentioned in `po/POTFILES.in`. For example `src/NPrefsWindow.cc` isn't and that's why its strings are missing from the po/pot files.
I added that file and ran `xgettext` to generate a new `po/nitrogen.pot` file to get those strings. However, there's a problem: they have a leading underscore and I don't know if that's normal. 
```
#: src/NPrefsWindow.cc:32
msgid "_Icon with captions"
msgstr ""
```
Is the underscore in ("_Icon") necessary? https://github.com/l3ib/nitrogen/blob/07888073e5c91051c84afba1bdfb21be2bc7524f/src/NPrefsWindow.cc#L31

Is it possible to also handle the "Preferences" and "Apply" translations (which I think are those stock icons you mentioned) internally in Nitrogen?

Either way, solving this is just a matter of adding the missing files which have translateable strings and updating the Nitrogen translation template file. The translations need updating as well.

<hr>

As for the actual bug: my bad. I have DATADIRNAME also defined in `m4/gettext.m4`. I was expecting it in the `configure.ac` file (I don't really know anything about makefiles).

In a clean source directory I ran `autoreconf -i`, `configure --prefix=/usr` and `make`. Then I ran strace on the new binary and it's STILL looking for the .mo files in `/usr//locale/...`, with a missing "share" between the two slashes.

When I do `configure --prefix=/usr DATADIRNAME=share`, then `make` and then run the binary, it's looking in the proper `/usr/share/locale/...` directory. 

Does anyone know why that's happening?

**Comment by daf** [comment]
> It seems that not all source files are mentioned in po/POTFILES.in. For example src/NPrefsWindow.cc isn't and that's why its strings are missing from the po/pot files.

Yeah, probably missed adding that back in the day.  The .pot files have certainly drifted from when they were generated.

>  However, there's a problem: they have a leading underscore and I don't know if that's normal.

They are - they signal to GTK to be keyboard accessors - hold down Alt and they will be underlined and selectable by that character.  Of course, they're defined with more than one using the same accessor key, which just cycles focus between all the matching ones.  Could stand to update those to all be unique.

> As for the actual bug: my bad. I have DATADIRNAME also defined in m4/gettext.m4. I was expecting it in the configure.ac file (I don't really know anything about makefiles).

It's also defined there for me, and I think it's supposed to be, but it seems like it doesn't carry through during compilation and maybe configuration.  I'm wading through gettext's docs now trying to understand, but my eyes are glazing over.

**Comment by daf** [comment]
Good news, I've got a commit (97fce2c) that seems to solve things.  I've pushed to a new branch that can collect additional translation related fixes before it merges, hopefully @dglava will have a chance to verify.

**Comment by dglava** [comment]
Yes, it's working. I just tested it and it's sourcing the files from the proper directory/path now (`/usr/share/locale...`).
